---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: nginx
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: docker.io/lpanza/tekton-cicd-test:024cd9859a5030e8ca4e9d59402ce4e35ad20f87
      # image: docker.io/library/nginx:1.22.1
        name: nginx
        resources: {}
status: {}
