---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: nginx-alpine
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-alpine
  name: nginx-alpine
  namespace: nginx-alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-alpine
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-alpine
    spec:
      containers:
      - image: docker.io/lpanza/tekton-cicd-test:6e0a8c3f1d41657c69b329c4fc279ec61b2ed6ea
      # image: docker.io/library/nginx:1.22.1-alpine
        name: nginx-alpine
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-alpine
  name: nginx-alpine
  namespace: nginx-alpine
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx-alpine
status:
  loadBalancer: {}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: nginx-alpine
  name: nginx-alpine
  namespace: nginx-alpine
spec:
  tls:
    termination: edge
  port:
    targetPort: 8080
  to:
    kind: ""
    name: nginx-alpine
    weight: null
status: {}
