---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: nginx-alpine
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-alpine
  name: nginx-alpine
  namespace: nginx-alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-alpine
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-alpine
    spec:
      containers:
      - image: nginx:alpine
        name: nginx-alpine
        resources: {}
status: {}
