---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: apache
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: apache
  name: apache
  namespace: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: apache
    spec:
      containers:
      - image: docker.io/lpanza/tekton-cicd-test:b79f0ae742cb485ab8073cde60e1f7c139de2232
        #image: docker.io/library/httpd:2.4.56
        name: apache
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: apache
  name: apache
  namespace: apache
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: apache
status:
  loadBalancer: {}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: apache
  name: apache
  namespace: apache
spec:
  tls:
    termination: edge
  port:
    targetPort: 8080
  to:
    kind: ""
    name: apache
    weight: null
status: {}
